//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerSpot.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Beer()
        {
            this.BeersContainers = new HashSet<BeersContainer>();
        }
    
        public int BeerID { get; set; }
        public string Name { get; set; }
        public Nullable<int> StyleID { get; set; }
        public decimal PricePerBeer { get; set; }
        public Nullable<decimal> ABV { get; set; }
        public int BrewerID { get; set; }
        public Nullable<int> BeerStatusID { get; set; }
        public string BeerImage { get; set; }
        public Nullable<bool> IsSeasonal { get; set; }
        public bool IsActive { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
    
        public virtual BeersStatu BeersStatu { get; set; }
        public virtual Brewer Brewer { get; set; }
        public virtual Style Style { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeersContainer> BeersContainers { get; set; }
    }
}
