//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerSpot.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeersContainer
    {
        public int BeersContainersID { get; set; }
        public int BeerID { get; set; }
        public int ContainerID { get; set; }
    
        public virtual Beer Beer { get; set; }
        public virtual Container Container { get; set; }
    }
}
